name: kanban
description: "A Kanban time tracking application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.1
  dio: ^5.4.3+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.5
  go_router: ^14.1.4
  kanban_board: ^0.1.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

